# Generated by Django 5.1.6 on 2025-07-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game_record", "0001_initial"),
        ("sudoku", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerecord",
            name="sudoku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_records",
                to="sudoku.sudoku",
                verbose_name="original sudoku",
            ),
        ),
    ]
