# Generated by Django 5.1.6 on 2025-07-11 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("game_record", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="player",
            ),
        ),
        migrations.AddIndex(
            model_name="gamerecord",
            index=models.Index(fields=["user", "status"], name="game_record_user_id_fdbf5a_idx"),
        ),
        migrations.AddIndex(
            model_name="gamerecord",
            index=models.Index(
                fields=["user", "created_at"], name="game_record_user_id_3ec43e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gamerecord",
            index=models.Index(fields=["user", "won"], name="game_record_user_id_b34a0b_idx"),
        ),
        migrations.AddIndex(
            model_name="gamerecord",
            index=models.Index(fields=["score"], name="game_record_score_bb4a1b_idx"),
        ),
        migrations.AddIndex(
            model_name="gamerecord",
            index=models.Index(fields=["created_at"], name="game_record_created_352140_idx"),
        ),
    ]
