default_stages: [pre-commit]

repos:
  - repo: local

    hooks:

    # Code formatting

    - id: ruff format
      name: ruff format
      language: python
      entry: ruff format
      types: [python]

    # Code analysis
    
    - id: ruff check
      name: ruff check
      language: python
      entry: ruff check .
      args: [--fix, --exit-non-zero-on-fix]
      types: [python]

    - id: mypy
      name: mypy
      language: python
      entry: mypy
      args: [--strict]
      types: [python]
      additional_dependencies:
        - django-stubs

    # Testing

    - id: django-pytest
      name: django-pytest
      language: python
      entry: pytest
      types: [python]
