services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: 
      context: .
      args:
        PYTHON_VERSION: 3.12
    command: ["/app/manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.12
    command: ["-m", "celery", "--workdir=/app", "-A", "app", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - web
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.12
    command: ["-m", "celery", "--workdir=/app", "-A", "app", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - web
    env_file:
      - .env

volumes:
  redis_data: