# Generated by Django 6.0.7 on 2026-07-11 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstats",
            name="lost_games",
            field=models.IntegerField(
                default=0,
                help_text="Total number of games lost by the user.",
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="lost games",
            ),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="win_rate",
            field=models.FloatField(
                default=0.0,
                help_text="Player's win rate.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="win rate",
            ),
        ),
        migrations.AddIndex(
            model_name="userstats",
            index=models.Index(
                fields=["-total_score", "-best_score"], name="user_userst_total_s_5b8ec4_idx"
            ),
        ),
    ]
