# Generated by Django 5.1.6 on 2025-03-20 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Sudoku",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
