# Generated by Django 5.1.6 on 2025-03-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudoku",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Hard", "Hard"),
                ],
                default="Unknown",
                max_length=10,
            ),
        ),
    ]
