# Generated by Django 5.1.6 on 2025-03-24 08:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='sudoku identifier')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('difficulty', models.CharField(choices=[('Unknown', 'Unknown'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Unknown', max_length=7, verbose_name='difficulty')),
                ('grid', models.CharField(default='000000000000000000000000000000000000000000000000000000000000000000000000000000000', max_length=81, validators=[django.core.validators.MinLengthValidator(limit_value=81)], verbose_name='grid')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Aborted', 'Aborted'), ('Invalid', 'Invalid')], default='Created', max_length=9, verbose_name='status')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'sudoku',
                'verbose_name_plural': 'sudokus',
            },
        ),
        migrations.CreateModel(
            name='SudokuSolution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='sudoku solution identifier')),
                ('grid', models.CharField(blank=True, max_length=81, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=81)], verbose_name='solution grid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
