# Generated by Django 5.1.6 on 2025-03-28 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sudoku', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sudokus', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='sudokusolution',
            name='sudoku',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='sudoku.sudoku', verbose_name='sudoku'),
        ),
    ]
