# Generated by Django 6.0.7 on 2026-07-11 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sudokusolution",
            options={"verbose_name": "sudoku solution", "verbose_name_plural": "sudoku solutions"},
        ),
        migrations.AddIndex(
            model_name="sudoku",
            index=models.Index(
                fields=["user", "-created_at"], name="sudoku_sudo_user_id_c10b40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sudoku",
            index=models.Index(fields=["created_at"], name="sudoku_sudo_created_c8362d_idx"),
        ),
    ]
