# Generated by Django 5.1.6 on 2025-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sudoku", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sudoku",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("easy", "Easy"),
                    ("medium", "Medium"),
                    ("hard", "Hard"),
                ],
                default="unknown",
                max_length=7,
                verbose_name="difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="sudoku",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("aborted", "Aborted"),
                    ("invalid", "Invalid"),
                ],
                default="created",
                max_length=9,
                verbose_name="status",
            ),
        ),
    ]
